### ISSUE TITLE
Hub code gets stuck on Raspberry Pi 3 

### ISSUE THREAD

**Issue by OrenLederman** [HumanDynamics/openbadge-hub-py#26]
When the hub code fails (see below) and restarts, it seems to "hang" when it tries to reset the bluetooth parameters again. 

openbadge-hub-py_1  | 2018-05-02 04:07:56,712 - DEBUG - SCAN: scan timestamp: 1525234063.000, voltage: 2.760, Devices in scan: 29
openbadge-hub-py_1  | 2018-05-02 04:07:56,714 - DEBUG - Setting last badge proximity timestamp to 1525234063
openbadge-hub-py_1  | 2018-05-02 04:07:56,715 - DEBUG - Sending update badge data to server, badge H43PLWQT2T : {'last_proximity_ts': 1525234063, 'last_audio_ts_fract': 660, 'last_audio_ts': 1525234066, 'last_seen_ts': 1525234075.933715, 'last_voltage': 2.765, 'observed_id': 364, 'last_contacted_ts': 1525234043.898249, 'last_unsync_ts': u'1525207856.660'}
openbadge-hub-py_1  | 2018-05-02 04:07:58,760 - INFO - Requesting device WT54XR1UQB from server...
openbadge-hub-py_1  | 2018-05-02 04:07:58,803 - INFO - [C2:E5:E8:61:33:F5] Connecting to C2:E5:E8:61:33:F5
openbadge-hub-py_1  | 2018-05-02 04:08:00,139 - ERROR - [C2:E5:E8:61:33:F5] failed pulling data
openbadge-hub-py_1  | 2018-05-02 04:08:00,140 - ERROR - [C2:E5:E8:61:33:F5] 1
openbadge-hub-py_1  | 2018-05-02 04:08:00,141 - ERROR - [C2:E5:E8:61:33:F5] Failed to connect to peripheral C2:E5:E8:61:33:F5, addr type: random
openbadge-hub-py_1  | 2018-05-02 04:08:00,142 - INFO - [C2:E5:E8:61:33:F5] Disconnecting from C2:E5:E8:61:33:F5
openbadge-hub-py_1  | 2018-05-02 04:08:00,143 - INFO - Errors pulling data.
openbadge-hub-py_1  | 2018-05-02 04:08:00,143 - INFO - No mic data ready
openbadge-hub-py_1  | 2018-05-02 04:08:00,144 - INFO - No proximity scans ready
openbadge-hub-py_1  | 2018-05-02 04:08:00,145 - DEBUG - Sending update badge data to server, badge WT54XR1UQB : {'last_proximity_ts': 1525234067, 'last_audio_ts_fract': 466, 'last_audio_ts': 1525234058, 'last_seen_ts': 1525233264.22164, 'last_voltage': 2.8, 'observed_id': 327, 'last_contacted_ts': u'1525234040.330', 'last_unsync_ts': u'1525207860.280'}
openbadge-hub-py_1  | 2018-05-02 04:08:02,209 - INFO - Requesting device MFLO4PT79R from server...
openbadge-hub-py_1  | 2018-05-02 04:08:02,254 - INFO - [D4:1C:A4:EB:29:FB] Connecting to D4:1C:A4:EB:29:FB
openbadge-hub-py_1  | 2018-05-02 04:08:03,990 - INFO - [D4:1C:A4:EB:29:FB] Connected
openbadge-hub-py_1  | 2018-05-02 04:08:03,991 - INFO - [D4:1C:A4:EB:29:FB] Sending status request (Badge id : 375 , project id : 22)
openbadge-hub-py_1  | 2018-05-02 04:08:04,032 - INFO - [D4:1C:A4:EB:29:FB] Got time ack
openbadge-hub-py_1  | 2018-05-02 04:08:04,033 - INFO - [D4:1C:A4:EB:29:FB] Badge datetime was: 3288462170,12860
openbadge-hub-py_1  | 2018-05-02 04:08:04,034 - INFO - [D4:1C:A4:EB:29:FB] Starting audio recording
openbadge-hub-py_1  | 2018-05-02 04:08:04,037 - ERROR - [D4:1C:A4:EB:29:FB] unexpected failure, unpack requires a string argument of length 6 ,Traceback (most recent call last):
openbadge-hub-py_1  |   File "/app/badge.py", line 593, in pull_data
openbadge-hub-py_1  |     self.sendStartRecRequest(RECORDING_TIMEOUT)  # start recording
openbadge-hub-py_1  |   File "/app/badge.py", line 416, in sendStartRecRequest
openbadge-hub-py_1  |     return self.conn.write('<cLHH',"1",long_epoch_seconds,ts_fract,timeout)
openbadge-hub-py_1  |   File "/app/badge.py", line 265, in write
openbadge-hub-py_1  |     return self.NrfReadWrite.write(s)
openbadge-hub-py_1  |   File "/app/nrf.py", line 47, in write
openbadge-hub-py_1  |     return self.tx.write(arr)
openbadge-hub-py_1  |   File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 148, in write
openbadge-hub-py_1  |     self.peripheral.writeCharacteristic(self.valHandle, val, withResponse)
openbadge-hub-py_1  |   File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 459, in writeCharacteristic
openbadge-hub-py_1  |     return self._getResp('wr')
openbadge-hub-py_1  |   File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 343, in _getResp
openbadge-hub-py_1  |     self.delegate.handleNotification(hnd, data)
openbadge-hub-py_1  |   File "/app/badge.py", line 196, in handleNotification
openbadge-hub-py_1  |     self.timestamp_sec,self.timestamp_ms = struct.unpack('<LH',data)
openbadge-hub-py_1  | error: unpack requires a string argument of length 6
openbadge-hub-py_1  | 
openbadge-hub-py_1  | 2018-05-02 04:08:04,038 - INFO - [D4:1C:A4:EB:29:FB] Disconnecting from D4:1C:A4:EB:29:FB
openbadge-hub-py_1  | Traceback (most recent call last):
openbadge-hub-py_1  |   File "./badge_hub.py", line 673, in <module>
openbadge-hub-py_1  |     pull_devices(mgr, mgrb, args.start_recording)
openbadge-hub-py_1  |   File "./badge_hub.py", line 467, in pull_devices
openbadge-hub-py_1  |     dialogue(b, activate_audio, activate_proximity, mode)
openbadge-hub-py_1  |   File "./badge_hub.py", line 198, in dialogue
openbadge-hub-py_1  |     ret = bdg.pull_data(activate_audio, activate_proximity)
openbadge-hub-py_1  |   File "/app/badge.py", line 669, in pull_data
openbadge-hub-py_1  |     self.disconnect()
openbadge-hub-py_1  |   File "/app/badge.py", line 398, in disconnect
openbadge-hub-py_1  |     self.conn.disconnect()
openbadge-hub-py_1  |   File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 376, in disconnect
openbadge-hub-py_1  |     self._getResp('stat')
openbadge-hub-py_1  |   File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 334, in _getResp
openbadge-hub-py_1  |     resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
openbadge-hub-py_1  |   File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 301, in _waitResp
openbadge-hub-py_1  |     raise BTLEException(BTLEException.INTERNAL_ERROR, "Unexpected response (%s)" % respType)
openbadge-hub-py_1  | bluepy.btle.BTLEException: Unexpected response (wr)
openbadge-hub-py_1  | /usr/local/lib/python2.7/dist-packages/dotenv/main.py:24: UserWarning: Not loading /app/.env - it doesn't exist.
openbadge-hub-py_1  |   warnings.warn("Not loading %s - it doesn't exist." % dotenv_path)
openbadge-hub-py_1  | 2018-05-02 04:08:05,474 - INFO - Resetting bluetooth
openbadge-hub-py_1  | 2018-05-02 04:08:05,481 - INFO - Setting bluetooth connection parameters
openbadge-hub-py_1  | 2018-05-02 04:08:05,481 - INFO - Raspberry Pi detected, changing bluetooth connection parameters

**Comment by OrenLederman** [comment]
I tried to SSH to the machine, and any bluetooth-related commands gets stuck. I suggest:
1. fix the bug that causes the code to fail (or at least catch the error and gracefully recover)
2. add a delay before starting again. might be able to do this using docker-compose settings

**Comment by OrenLederman** [comment]
Fixed the issue with disconnect (#27). However, there will still be a problem if the code crashes and restarts.
